name: EpicJobs
version: '$version'
main: com.epicquestz.epicjobs.EpicJobs
api-version: '1.20'
authors: [StealWonders]
description: Helps manage builder tasks and jobs.
website: https://www.epicquestz.com

depend: [PlayerUUIDCache]
softdepend: [Multiverse-Core, Hyperverse]

commands:
  # handled by the Aikar annotation command framework (ACF).

