name: EpicJobs
version: '$version'
main: com.epicquestz.epicjobs.EpicJobs
api-version: '1.20'
authors: [StealWonders]
description: Helps manage builder tasks and jobs.
website: https://www.epicquestz.com

softdepend: [Multiverse-Core, Hyperverse]

commands:
  # handled by the 'cloud command framework'
