name: EpicJobs
version: @version@
main: de.stealwonders.epicjobs.EpicJobs
api-version: 1.13
authors: [StealWonders]
description: Helps manage builder tasks and jobs.
website: www.stealwonders.de

depend: [PlayerUUIDCache]

commands:
  # handled by the Aikar annotation command framework (ACF).

